---
- name: add nginx repository
  yum:
    name: http://nginx.org/packages/centos/{{ ansible_distribution_major_version }}/noarch/RPMS/nginx-release-centos-{{ ansible_distribution_major_version }}-0.el{{ ansible_distribution_major_version }}.ngx.noarch.rpm
    state: present
  tags:
    - nginx

- name: install nginx
  yum: name=nginx state=present
  tags:
    - nginx

- name: configure nginx as startup service
  service: name=nginx state=started enabled=yes
  tags:
    - configuration
    - nginx
