---
- include: install.yml
  tags: [web-server, nginx, install, nginx-install]

- include: configure.yml
  tags: [web-server, nginx, configuration, nginx-configuration]

- include: sites.yml
  when: nginx_sites is defined
  tags: [web-server, nginx, nginx-site]
