---
- name: register currently present site configurations
  shell: (cd /etc/nginx/conf.d; ls -1 *.conf) | cut -d'.' -f1
  register: current_site_list
  changed_when: false

- name: remove unmanaged site configurations
  file: name=/etc/nginx/conf.d/{{ item }}.conf state=absent
  with_items: current_site_list.stdout_lines
  when: item not in nginx_sites|map(attribute='name')
  notify:
    - reload nginx
  tags: [cleanup]

- name: create site configuration files
  template: src=site.j2 dest=/etc/nginx/conf.d/{{ item.name }}.conf
  notify:
    - reload nginx
  with_items: nginx_sites
